# Generated by Django 6.0.1 on 2026-02-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_shortenedurl_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
