# Generated by Django 6.0.1 on 2026-02-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_shortenedurl_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
