# Generated by Django 6.0.1 on 2026-02-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_shortenedurl_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='last_clicked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
